# Generated by Django 2.2.1 on 2019-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dos',
            name='accuse_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dos',
            name='description_action',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dos',
            name='description_mesure',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dos',
            name='heure_operation',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dos',
            name='identification_beneficiaire',
            field=models.CharField(choices=[('Carte identité nationale', 'Carte identité nationale'), ('Passeport', 'Passeport'), ('Certificat de naissance', 'Certificat de naissance'), ('Permis de conduire', 'Permis de conduire'), ('Titre de séjour', 'Titre de séjour'), ('Pays de citoyenneté', 'Pays de citoyenneté'), ('Autre', 'Autre')], max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='identification_individu',
            field=models.CharField(choices=[('Carte identité nationale', 'Carte identité nationale'), ('Passeport', 'Passeport'), ('Certificat de naissance', 'Certificat de naissance'), ('Permis de conduire', 'Permis de conduire'), ('Titre de séjour', 'Titre de séjour'), ('Pays de citoyenneté', 'Pays de citoyenneté'), ('Autre', 'Autre')], max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='intitule_compte',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='lieu_operation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='nom_beneficiaire',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='nom_etablissement',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='nom_individu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='numero_declaration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dos',
            name='prenom_beneficiaire',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='prenom_individu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='profession_beneficiaire',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='profession_individu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dos',
            name='relation',
            field=models.TextField(max_length=1000),
        ),
    ]
